version: '3'

services:
  influx:
    image: icnslab/edge-cloud-mon-influxdb:1.4.3-rpi3
    ports:
      - 0.0.0.0:8086:8086
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: icnslab/edge-cloud-mon-grafana:v4.6.3-rpi3
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      - influx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: icnslab/edge-cloud-mon-cadvisor:influx-rss-memory-0.28.3v-rpi3
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb 
             -storage_driver_db=cadvisor -storage_driver_host=influx:8086 
             -storage_driver_buffer_duration=5s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global
